# Generated by Django 6.0.6 on 2026-06-26 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, unique=True, verbose_name='نام انگلیسی دسته\u200cبندی')),
                ('title_fa', models.CharField(max_length=100, verbose_name='نام فارسی دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='اسلاگ (سئو)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MacApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='نام انگلیسی برنامه')),
                ('title_fa', models.CharField(max_length=200, verbose_name='نام فارسی برنامه')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='اسلاگ (سئو)')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('icon', models.ImageField(upload_to='apps/icons/', verbose_name='آیکون برنامه')),
                ('version', models.CharField(max_length=50, verbose_name='آخرین نسخه')),
                ('developer', models.CharField(blank=True, max_length=100, null=True, verbose_name='توسعه\u200cدهنده')),
                ('file_size', models.CharField(max_length=50, verbose_name='حجم فایل')),
                ('min_macos', models.CharField(max_length=100, verbose_name='حداقل سیستم\u200cعامل مورد نیاز')),
                ('architecture', models.CharField(choices=[('intel', 'Intel Only (مک\u200cهای قدیمی)'), ('m_series', 'Apple Silicon Native (سری M)'), ('universal', 'Universal (هر دو سری پردازنده)')], default='universal', max_length=20, verbose_name='معماری پردازنده')),
                ('license_status', models.CharField(choices=[('free', 'کاملاً رایگان'), ('cracked', 'کرک شده'), ('pre_activated', 'از قبل فعال شده')], default='cracked', max_length=20, verbose_name='وضعیت لایسنس')),
                ('installation_guide', models.TextField(blank=True, null=True, verbose_name='راهنمای نصب و فعال\u200cسازی')),
                ('views_count', models.PositiveIntegerField(default=True, verbose_name='تعداد بازدید')),
                ('is_published', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به\u200cروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='app.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'نرم\u200cافزار مک',
                'verbose_name_plural': 'نرم\u200cافزارهای مک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان لینک')),
                ('url', models.URLField(max_length=500, verbose_name='آدرس لینک دانلود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_link', to='app.macapp', verbose_name='نرم\u200cافزار مربوطه')),
            ],
            options={
                'verbose_name': 'لینک دانلود',
                'verbose_name_plural': 'لینک\u200cهای دانلود',
            },
        ),
    ]
