# Generated by Django 6.0.6 on 2026-06-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='app.macapp', verbose_name='نرم\u200cافزار مربوطه'),
        ),
    ]
