# Generated by Django 6.0.6 on 2026-06-21 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleIdOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_firstname', models.CharField(max_length=50, verbose_name='نام (فارسی)')),
                ('fa_lastname', models.CharField(max_length=100, verbose_name='نام خانوادگی (فارسی)')),
                ('en_firstname', models.CharField(max_length=50, verbose_name='نام (انگلیسی)')),
                ('en_lastname', models.CharField(max_length=100, verbose_name='نام خانوادگی (انگلیسی)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل کاربر')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار ساخت'), ('processing', 'در حال انجام'), ('completed', 'تحویل داده شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apple_id_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
