# Generated by Django 6.0.6 on 2026-06-22 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تیتر')),
                ('department', models.CharField(choices=[('appleid', 'پشتیبانی خدمات اپل آیدی'), ('apps', 'مشکلات دانلود و نصب نرم\u200cافزار'), ('financial', 'امور مالی و پرداخت'), ('general', 'سوالات عمومی')], default='appleid', max_length=20, verbose_name='بخش مربوطه')),
                ('priroty', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('open', 'باز / در انتظار پاسخ پشتیبان'), ('answered', 'پاسخ داده شده'), ('user_replied', 'پاسخ کاربر'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت تیکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت\u200cها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachment/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده پیام')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='تیکت مربوطه')),
            ],
            options={
                'verbose_name': 'پیام\u200cهای تیکت',
                'ordering': ['-created_at'],
            },
        ),
    ]
